"""Kalan dil dosyalarını toplu oluştur"""
import json, os

LOCALES_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "frontend", "src", "i18n", "locales")

# en.json'u temel al
with open(os.path.join(LOCALES_DIR, "en.json"), "r", encoding="utf-8") as f:
    en = json.load(f)

TRANSLATIONS = {
    "ur": {"lang":"اردو","common.save":"محفوظ کریں","common.cancel":"منسوخ","common.delete":"حذف کریں","common.edit":"ترمیم","common.done":"ہو گیا","common.next":"اگلا","common.back":"واپس","common.search":"تلاش","common.loading":"لوڈ ہو رہا ہے...","common.error":"خرابی","common.success":"کامیاب","common.retry":"دوبارہ کوشش","common.close":"بند کریں","common.confirm":"تصدیق کریں","common.yes":"ہاں","common.no":"نہیں","common.ok":"ٹھیک ہے","common.send":"بھیجیں","common.share":"شیئر کریں","common.report":"رپورٹ","common.block":"بلاک کریں","common.unblock":"ان بلاک","common.follow":"فالو کریں","common.unfollow":"ان فالو","common.following":"فالوئنگ","common.followers":"فالوورز","common.posts":"پوسٹس","common.likes":"لائکس","common.comments":"تبصرے","common.seeAll":"سب دیکھیں","common.noResults":"کوئی نتیجہ نہیں ملا","common.connectionError":"کنکشن کی خرابی","common.create":"بنائیں","common.unknown":"نامعلوم","auth.login":"لاگ ان","auth.register":"سائن اپ","auth.logout":"لاگ آؤٹ","auth.email":"ای میل","auth.password":"پاسورڈ","auth.username":"صارف نام","auth.forgotPassword":"پاسورڈ بھول گئے؟","auth.welcomeTitle":"ساتھ میں موسیقی دریافت کریں","auth.or":"یا","home.trending":"ٹرینڈنگ","home.forYou":"آپ کے لیے","home.newReleases":"نئی ریلیز","home.topCharts":"ٹاپ 10","home.story":"سٹوری","home.welcome":"SocialBeats میں خوش آمدید","feed.feed":"فیڈ","feed.newPost":"نئی پوسٹ","feed.like":"پسند","feed.comment":"تبصرہ","feed.share":"شیئر","messages.messages":"پیغامات","messages.newMessage":"نیا پیغام","messages.calls":"کالز","messages.online":"آن لائن","music.nowPlaying":"ابھی چل رہا ہے","music.playlist":"پلے لسٹ","music.lyrics":"بول","music.songs":"گانے","music.artists":"فنکار","notifications.notifications":"اطلاعات","settings.settings":"ترتیبات","settings.account":"اکاؤنٹ","settings.privacy":"رازداری","settings.language":"زبان","settings.theme":"تھیم","settings.security":"سیکیورٹی","settings.help":"مدد","settings.about":"کے بارے میں","search.search":"تلاش","time.justNow":"ابھی ابھی"},
    "ms": {"lang":"Bahasa Melayu","common.save":"Simpan","common.cancel":"Batal","common.delete":"Padam","common.edit":"Edit","common.done":"Selesai","common.next":"Seterusnya","common.back":"Kembali","common.search":"Cari","common.loading":"Memuatkan...","common.error":"Ralat","common.success":"Berjaya","common.retry":"Cuba Lagi","common.close":"Tutup","common.confirm":"Sahkan","common.yes":"Ya","common.no":"Tidak","common.ok":"OK","common.send":"Hantar","common.share":"Kongsi","common.report":"Laporkan","common.block":"Sekat","common.unblock":"Nyahsekat","common.follow":"Ikuti","common.unfollow":"Nyahikuti","common.following":"Mengikuti","common.followers":"Pengikut","common.posts":"Hantaran","common.likes":"Suka","common.comments":"Komen","common.seeAll":"Lihat Semua","common.noResults":"Tiada hasil ditemui","common.connectionError":"Ralat sambungan","common.create":"Cipta","common.unknown":"Tidak diketahui","auth.login":"Log Masuk","auth.register":"Daftar","auth.logout":"Log Keluar","auth.email":"Emel","auth.password":"Kata Laluan","auth.username":"Nama Pengguna","auth.forgotPassword":"Lupa kata laluan?","auth.welcomeTitle":"Temui muzik bersama","auth.or":"atau","home.trending":"Trending","home.forYou":"Untuk Anda","home.newReleases":"Keluaran Baharu","home.topCharts":"Top 10","home.story":"Cerita","home.welcome":"Selamat datang ke SocialBeats","feed.feed":"Suapan","feed.newPost":"Hantaran Baharu","feed.like":"Suka","feed.comment":"Komen","feed.share":"Kongsi","messages.messages":"Mesej","messages.newMessage":"Mesej Baharu","messages.calls":"Panggilan","messages.online":"Dalam Talian","music.nowPlaying":"Sedang Dimainkan","music.playlist":"Senarai Main","music.lyrics":"Lirik","music.songs":"Lagu","music.artists":"Artis","notifications.notifications":"Pemberitahuan","settings.settings":"Tetapan","settings.account":"Akaun","settings.privacy":"Privasi","settings.language":"Bahasa","settings.theme":"Tema","settings.security":"Keselamatan","settings.help":"Bantuan","settings.about":"Perihal","search.search":"Cari","time.justNow":"baru sahaja"},
    "pl": {"lang":"Polski","common.save":"Zapisz","common.cancel":"Anuluj","common.delete":"Usuń","common.edit":"Edytuj","common.done":"Gotowe","common.next":"Dalej","common.back":"Wstecz","common.search":"Szukaj","common.loading":"Ładowanie...","common.error":"Błąd","common.success":"Sukces","common.retry":"Ponów","common.close":"Zamknij","common.confirm":"Potwierdź","common.yes":"Tak","common.no":"Nie","common.ok":"OK","common.send":"Wyślij","common.share":"Udostępnij","common.report":"Zgłoś","common.block":"Zablokuj","common.unblock":"Odblokuj","common.follow":"Obserwuj","common.unfollow":"Przestań obserwować","common.following":"Obserwowani","common.followers":"Obserwujący","common.posts":"Posty","common.likes":"Polubienia","common.comments":"Komentarze","common.seeAll":"Zobacz wszystko","common.noResults":"Brak wyników","common.connectionError":"Błąd połączenia","common.create":"Utwórz","common.unknown":"Nieznane","auth.login":"Zaloguj się","auth.register":"Zarejestruj się","auth.logout":"Wyloguj","auth.email":"E-mail","auth.password":"Hasło","auth.username":"Nazwa użytkownika","auth.forgotPassword":"Zapomniałeś hasła?","auth.welcomeTitle":"Odkrywaj muzykę razem","auth.or":"lub","home.trending":"Na czasie","home.forYou":"Dla Ciebie","home.newReleases":"Nowości","home.topCharts":"Top 10","home.story":"Relacja","home.welcome":"Witaj w SocialBeats","feed.feed":"Aktualności","feed.newPost":"Nowy post","feed.like":"Lubię","feed.comment":"Komentarz","feed.share":"Udostępnij","messages.messages":"Wiadomości","messages.newMessage":"Nowa wiadomość","messages.calls":"Połączenia","messages.online":"Online","music.nowPlaying":"Teraz gramy","music.playlist":"Playlista","music.lyrics":"Teksty","music.songs":"Piosenki","music.artists":"Artyści","notifications.notifications":"Powiadomienia","settings.settings":"Ustawienia","settings.account":"Konto","settings.privacy":"Prywatność","settings.language":"Język","settings.theme":"Motyw","settings.security":"Bezpieczeństwo","settings.help":"Pomoc","settings.about":"O aplikacji","search.search":"Szukaj","time.justNow":"przed chwilą"},
    "fil": {"lang":"Filipino","common.save":"I-save","common.cancel":"Kanselahin","common.delete":"Burahin","common.edit":"I-edit","common.done":"Tapos","common.next":"Susunod","common.back":"Bumalik","common.search":"Maghanap","common.loading":"Naglo-load...","common.error":"Error","common.success":"Tagumpay","common.retry":"Subukang muli","common.close":"Isara","common.confirm":"Kumpirmahin","common.yes":"Oo","common.no":"Hindi","common.ok":"OK","common.send":"Ipadala","common.share":"Ibahagi","common.report":"Iulat","common.block":"I-block","common.unblock":"I-unblock","common.follow":"Sundan","common.unfollow":"I-unfollow","common.following":"Sinusundan","common.followers":"Mga tagasunod","common.posts":"Mga post","common.likes":"Mga like","common.comments":"Mga komento","common.seeAll":"Tingnan lahat","common.noResults":"Walang resulta","common.connectionError":"Error sa koneksyon","common.create":"Gumawa","common.unknown":"Hindi alam","auth.login":"Mag-log in","auth.register":"Mag-sign up","auth.logout":"Mag-log out","auth.email":"Email","auth.password":"Password","auth.username":"Username","auth.forgotPassword":"Nakalimutan ang password?","auth.welcomeTitle":"Tuklasin ang musika nang magkasama","auth.or":"o","home.trending":"Trending","home.forYou":"Para sa iyo","home.newReleases":"Bagong labas","home.topCharts":"Top 10","home.story":"Kwento","home.welcome":"Maligayang pagdating sa SocialBeats","feed.feed":"Feed","feed.newPost":"Bagong post","feed.like":"Like","feed.comment":"Komento","feed.share":"Ibahagi","messages.messages":"Mga mensahe","messages.newMessage":"Bagong mensahe","messages.calls":"Mga tawag","messages.online":"Online","music.nowPlaying":"Pinapatugtog ngayon","music.playlist":"Playlist","music.lyrics":"Lyrics","music.songs":"Mga kanta","music.artists":"Mga artist","notifications.notifications":"Mga notipikasyon","settings.settings":"Mga setting","settings.account":"Account","settings.privacy":"Privacy","settings.language":"Wika","settings.theme":"Tema","settings.security":"Seguridad","settings.help":"Tulong","settings.about":"Tungkol sa","search.search":"Maghanap","time.justNow":"kamakailan lang"},
    "bn": {"lang":"বাংলা","common.save":"সংরক্ষণ","common.cancel":"বাতিল","common.delete":"মুছুন","common.edit":"সম্পাদনা","common.done":"সম্পন্ন","common.next":"পরবর্তী","common.back":"ফিরে যান","common.search":"খুঁজুন","common.loading":"লোড হচ্ছে...","common.error":"ত্রুটি","common.success":"সফল","common.retry":"পুনরায় চেষ্টা","common.close":"বন্ধ","common.confirm":"নিশ্চিত করুন","common.yes":"হ্যাঁ","common.no":"না","common.ok":"ঠিক আছে","common.send":"পাঠান","common.share":"শেয়ার করুন","common.report":"রিপোর্ট","common.block":"ব্লক করুন","common.unblock":"আনব্লক","common.follow":"ফলো করুন","common.unfollow":"আনফলো","common.following":"ফলো করছেন","common.followers":"ফলোয়ার","common.posts":"পোস্ট","common.likes":"লাইক","common.comments":"মন্তব্য","common.seeAll":"সব দেখুন","common.noResults":"কোনো ফলাফল পাওয়া যায়নি","common.connectionError":"সংযোগ ত্রুটি","common.create":"তৈরি করুন","common.unknown":"অজানা","auth.login":"লগ ইন","auth.register":"সাইন আপ","auth.logout":"লগ আউট","auth.email":"ইমেইল","auth.password":"পাসওয়ার্ড","auth.username":"ব্যবহারকারীর নাম","auth.forgotPassword":"পাসওয়ার্ড ভুলে গেছেন?","auth.welcomeTitle":"একসাথে সঙ্গীত আবিষ্কার করুন","auth.or":"অথবা","home.trending":"ট্রেন্ডিং","home.forYou":"আপনার জন্য","home.newReleases":"নতুন মুক্তি","home.topCharts":"শীর্ষ ১০","home.story":"স্টোরি","home.welcome":"SocialBeats-এ স্বাগতম","feed.feed":"ফিড","feed.newPost":"নতুন পোস্ট","feed.like":"পছন্দ","feed.comment":"মন্তব্য","feed.share":"শেয়ার","messages.messages":"বার্তা","messages.newMessage":"নতুন বার্তা","messages.calls":"কল","messages.online":"অনলাইন","music.nowPlaying":"এখন বাজছে","music.playlist":"প্লেলিস্ট","music.lyrics":"গানের কথা","music.songs":"গান","music.artists":"শিল্পী","notifications.notifications":"বিজ্ঞপ্তি","settings.settings":"সেটিংস","settings.account":"অ্যাকাউন্ট","settings.privacy":"গোপনীয়তা","settings.language":"ভাষা","settings.theme":"থিম","settings.security":"নিরাপত্তা","settings.help":"সাহায্য","settings.about":"সম্পর্কে","search.search":"খুঁজুন","time.justNow":"এইমাত্র"},
    "ta": {"lang":"தமிழ்","common.save":"சேமி","common.cancel":"ரத்து","common.delete":"நீக்கு","common.edit":"திருத்து","common.done":"முடிந்தது","common.next":"அடுத்து","common.back":"பின்செல்","common.search":"தேடு","common.loading":"ஏற்றுகிறது...","common.error":"பிழை","common.success":"வெற்றி","common.retry":"மீண்டும் முயற்சி","common.close":"மூடு","common.confirm":"உறுதிசெய்","common.yes":"ஆம்","common.no":"இல்லை","common.ok":"சரி","common.send":"அனுப்பு","common.share":"பகிர்","common.report":"புகார்","common.block":"தடை","common.unblock":"தடை நீக்கு","common.follow":"பின்தொடர்","common.unfollow":"பின்தொடர வேண்டாம்","common.following":"பின்தொடர்கிறது","common.followers":"பின்தொடர்பவர்கள்","common.posts":"இடுகைகள்","common.likes":"விருப்பங்கள்","common.comments":"கருத்துகள்","common.seeAll":"அனைத்தையும் காண்","common.noResults":"முடிவுகள் இல்லை","common.connectionError":"இணைப்புப் பிழை","common.create":"உருவாக்கு","common.unknown":"தெரியவில்லை","auth.login":"உள்நுழை","auth.register":"பதிவுசெய்","auth.logout":"வெளியேறு","auth.email":"மின்னஞ்சல்","auth.password":"கடவுச்சொல்","auth.username":"பயனர்பெயர்","auth.forgotPassword":"கடவுச்சொல் மறந்துவிட்டதா?","auth.welcomeTitle":"இசையை ஒன்றாகக் கண்டறியுங்கள்","auth.or":"அல்லது","home.trending":"டிரெண்டிங்","home.forYou":"உங்களுக்காக","home.story":"ஸ்டோரி","home.welcome":"SocialBeats-க்கு வருக","feed.feed":"ஊட்டம்","messages.messages":"செய்திகள்","music.nowPlaying":"இப்போது இயங்குகிறது","music.songs":"பாடல்கள்","notifications.notifications":"அறிவிப்புகள்","settings.settings":"அமைப்புகள்","settings.language":"மொழி","search.search":"தேடு","time.justNow":"இப்போதே"},
    "te": {"lang":"తెలుగు","common.save":"సేవ్","common.cancel":"రద్దు","common.delete":"తొలగించు","common.edit":"సవరించు","common.done":"పూర్తయింది","common.next":"తదుపరి","common.back":"వెనుకకు","common.search":"వెతుకు","common.loading":"లోడ్ అవుతోంది...","common.error":"లోపం","common.success":"విజయం","common.retry":"మళ్ళీ ప్రయత్నించు","common.close":"మూసివేయి","common.confirm":"ధృవీకరించు","common.yes":"అవును","common.no":"కాదు","common.ok":"సరే","common.send":"పంపు","common.share":"షేర్","common.follow":"ఫాలో","common.unfollow":"అన్‌ఫాలో","common.followers":"ఫాలోవర్లు","common.posts":"పోస్ట్‌లు","common.likes":"లైక్‌లు","common.comments":"వ్యాఖ్యలు","common.seeAll":"అన్నీ చూడు","common.noResults":"ఫలితాలు లేవు","common.create":"సృష్టించు","common.unknown":"తెలియదు","auth.login":"లాగిన్","auth.register":"సైన్ అప్","auth.logout":"లాగ్ అవుట్","auth.email":"ఇమెయిల్","auth.password":"పాస్‌వర్డ్","auth.username":"వినియోగదారు పేరు","auth.welcomeTitle":"కలిసి సంగీతాన్ని కనుగొనండి","auth.or":"లేదా","home.trending":"ట్రెండింగ్","home.forYou":"మీ కోసం","home.story":"స్టోరీ","home.welcome":"SocialBeats కి స్వాగతం","feed.feed":"ఫీడ్","messages.messages":"సందేశాలు","music.nowPlaying":"ఇప్పుడు ప్లే అవుతోంది","music.songs":"పాటలు","notifications.notifications":"నోటిఫికేషన్లు","settings.settings":"సెట్టింగ్స్","settings.language":"భాష","search.search":"వెతుకు","time.justNow":"ఇప్పుడే"},
    "af": {"lang":"Afrikaans","common.save":"Stoor","common.cancel":"Kanselleer","common.delete":"Verwyder","common.edit":"Wysig","common.done":"Klaar","common.next":"Volgende","common.back":"Terug","common.search":"Soek","common.loading":"Laai...","common.error":"Fout","common.success":"Sukses","common.retry":"Probeer weer","common.close":"Sluit","common.confirm":"Bevestig","common.yes":"Ja","common.no":"Nee","common.ok":"OK","common.send":"Stuur","common.share":"Deel","common.follow":"Volg","common.unfollow":"Ontvolg","common.following":"Volg","common.followers":"Volgelinge","common.posts":"Plasings","common.likes":"Laaik","common.comments":"Kommentaar","common.seeAll":"Sien alles","common.noResults":"Geen resultate nie","common.create":"Skep","common.unknown":"Onbekend","auth.login":"Teken in","auth.register":"Registreer","auth.logout":"Teken uit","auth.email":"E-pos","auth.password":"Wagwoord","auth.username":"Gebruikersnaam","auth.welcomeTitle":"Ontdek musiek saam","auth.or":"of","home.trending":"Gewild","home.forYou":"Vir jou","home.story":"Storie","home.welcome":"Welkom by SocialBeats","feed.feed":"Voer","messages.messages":"Boodskappe","music.nowPlaying":"Speel nou","music.songs":"Liedjies","notifications.notifications":"Kennisgewings","settings.settings":"Instellings","settings.language":"Taal","search.search":"Soek","time.justNow":"nou net"},
    "zu": {"lang":"isiZulu","common.save":"Gcina","common.cancel":"Khansela","common.delete":"Susa","common.edit":"Hlela","common.done":"Kwenziwe","common.next":"Okulandelayo","common.back":"Emuva","common.search":"Sesha","common.loading":"Iyalayisha...","common.error":"Iphutha","common.success":"Impumelelo","common.close":"Vala","common.confirm":"Qinisekisa","common.yes":"Yebo","common.no":"Cha","common.ok":"Kulungile","common.send":"Thumela","common.share":"Yabelana","common.follow":"Landela","common.followers":"Abalandeli","common.posts":"Okuthunyelwe","common.likes":"Okuthandwayo","common.comments":"Amazwana","common.seeAll":"Bona konke","common.noResults":"Awekho amaphutha","common.create":"Dala","auth.login":"Ngena","auth.register":"Bhalisa","auth.logout":"Phuma","auth.email":"I-imeyili","auth.password":"Iphasiwedi","auth.welcomeTitle":"Thola umculo ndawonye","auth.or":"noma","home.trending":"Okudumile","home.forYou":"Okwakho","home.story":"Indaba","home.welcome":"Siyakwamukela ku-SocialBeats","feed.feed":"Ukudla","messages.messages":"Imilayezo","music.nowPlaying":"Okudlalayo manje","music.songs":"Izingoma","notifications.notifications":"Izaziso","settings.settings":"Izilungiselelo","settings.language":"Ulimi","search.search":"Sesha","time.justNow":"manje nje"},
    "ha": {"lang":"Hausa","common.save":"Ajiye","common.cancel":"Soke","common.delete":"Share","common.edit":"Gyara","common.done":"An gama","common.next":"Na gaba","common.back":"Komawa","common.search":"Nema","common.loading":"Ana lodawa...","common.error":"Kuskure","common.success":"Nasara","common.close":"Rufe","common.confirm":"Tabbatar","common.yes":"Eh","common.no":"A'a","common.ok":"To","common.send":"Aika","common.share":"Raba","common.follow":"Bi","common.followers":"Masu bi","common.posts":"Abubuwan da aka buga","common.likes":"Abubuwan da aka so","common.comments":"Sharhi","common.seeAll":"Duba duka","common.create":"Ƙirƙira","auth.login":"Shiga","auth.register":"Yi rajista","auth.logout":"Fita","auth.email":"Imel","auth.password":"Kalmar sirri","auth.welcomeTitle":"Gano kiɗa tare","auth.or":"ko","home.trending":"Abin da ke shahara","home.forYou":"A gare ka","home.story":"Labari","home.welcome":"Barka da zuwa SocialBeats","feed.feed":"Abinci","messages.messages":"Saƙonni","music.nowPlaying":"Ana kunna yanzu","music.songs":"Waƙoƙi","notifications.notifications":"Sanarwa","settings.settings":"Saituna","settings.language":"Harshe","search.search":"Nema","time.justNow":"yanzu nan"},
    "yo": {"lang":"Yorùbá","common.save":"Fi pamọ́","common.cancel":"Fagilee","common.delete":"Pa rẹ́","common.edit":"Ṣàtúnṣe","common.done":"Ti parí","common.next":"Tó kàn","common.back":"Padà","common.search":"Wá","common.loading":"Ń gbé kalẹ̀...","common.error":"Àṣìṣe","common.success":"Àṣeyọrí","common.close":"Pa dé","common.confirm":"Jẹ́rìísí","common.yes":"Bẹ́ẹ̀ni","common.no":"Rárá","common.ok":"Ó dára","common.send":"Fi ránṣẹ́","common.share":"Pín","common.follow":"Tẹ̀lé","common.followers":"Àwọn olùtẹ̀lé","common.posts":"Àwọn ìfiranṣẹ́","common.likes":"Àwọn ìfẹ́ràn","common.comments":"Àwọn àlàyé","common.seeAll":"Wo gbogbo rẹ̀","common.create":"Ṣẹ̀dá","auth.login":"Wọlé","auth.register":"Forúkọ sílẹ̀","auth.logout":"Jáde","auth.email":"Ímeèlì","auth.password":"Ọ̀rọ̀ aṣínà","auth.welcomeTitle":"Ṣàwárí orin pa pọ̀","auth.or":"tàbí","home.trending":"Ohun tó ń trend","home.forYou":"Fún ọ","home.story":"Ìtàn","home.welcome":"Ẹ kú àbọ̀ sí SocialBeats","feed.feed":"Ìjẹun","messages.messages":"Àwọn ifiranṣẹ́","music.nowPlaying":"Ń ṣeré báyìí","music.songs":"Orin","notifications.notifications":"Ìwífún","settings.settings":"Ètò","settings.language":"Èdè","search.search":"Wá","time.justNow":"ní ìsinsìnyí"},
    "nl": {"lang":"Nederlands","common.save":"Opslaan","common.cancel":"Annuleren","common.delete":"Verwijderen","common.edit":"Bewerken","common.done":"Klaar","common.next":"Volgende","common.back":"Terug","common.search":"Zoeken","common.loading":"Laden...","common.error":"Fout","common.success":"Gelukt","common.retry":"Opnieuw proberen","common.close":"Sluiten","common.confirm":"Bevestigen","common.yes":"Ja","common.no":"Nee","common.ok":"OK","common.send":"Verzenden","common.share":"Delen","common.report":"Melden","common.block":"Blokkeren","common.unblock":"Deblokkeren","common.follow":"Volgen","common.unfollow":"Ontvolgen","common.following":"Volgend","common.followers":"Volgers","common.posts":"Berichten","common.likes":"Likes","common.comments":"Reacties","common.seeAll":"Alles bekijken","common.noResults":"Geen resultaten gevonden","common.connectionError":"Verbindingsfout","common.create":"Aanmaken","common.unknown":"Onbekend","auth.login":"Inloggen","auth.register":"Registreren","auth.logout":"Uitloggen","auth.email":"E-mail","auth.password":"Wachtwoord","auth.username":"Gebruikersnaam","auth.forgotPassword":"Wachtwoord vergeten?","auth.welcomeTitle":"Ontdek muziek samen","auth.or":"of","home.trending":"Trending","home.forYou":"Voor jou","home.newReleases":"Nieuwe releases","home.topCharts":"Top 10","home.story":"Verhaal","home.welcome":"Welkom bij SocialBeats","feed.feed":"Feed","feed.newPost":"Nieuw bericht","feed.like":"Vind ik leuk","feed.comment":"Reactie","feed.share":"Delen","messages.messages":"Berichten","messages.newMessage":"Nieuw bericht","messages.calls":"Oproepen","messages.online":"Online","music.nowPlaying":"Nu aan het spelen","music.playlist":"Afspeellijst","music.lyrics":"Songteksten","music.songs":"Nummers","music.artists":"Artiesten","notifications.notifications":"Meldingen","settings.settings":"Instellingen","settings.account":"Account","settings.privacy":"Privacy","settings.language":"Taal","settings.theme":"Thema","settings.security":"Beveiliging","settings.help":"Help","settings.about":"Over","search.search":"Zoeken","time.justNow":"zojuist"},
    "uk": {"lang":"Українська","common.save":"Зберегти","common.cancel":"Скасувати","common.delete":"Видалити","common.edit":"Редагувати","common.done":"Готово","common.next":"Далі","common.back":"Назад","common.search":"Пошук","common.loading":"Завантаження...","common.error":"Помилка","common.success":"Успішно","common.retry":"Повторити","common.close":"Закрити","common.confirm":"Підтвердити","common.yes":"Так","common.no":"Ні","common.ok":"OK","common.send":"Надіслати","common.share":"Поділитися","common.report":"Поскаржитися","common.block":"Заблокувати","common.unblock":"Розблокувати","common.follow":"Підписатися","common.unfollow":"Відписатися","common.following":"Підписки","common.followers":"Підписники","common.posts":"Пости","common.likes":"Вподобання","common.comments":"Коментарі","common.seeAll":"Дивитися все","common.noResults":"Нічого не знайдено","common.connectionError":"Помилка з'єднання","common.create":"Створити","common.unknown":"Невідомо","auth.login":"Увійти","auth.register":"Зареєструватися","auth.logout":"Вийти","auth.email":"Електронна пошта","auth.password":"Пароль","auth.username":"Ім'я користувача","auth.forgotPassword":"Забули пароль?","auth.welcomeTitle":"Відкривайте музику разом","auth.or":"або","home.trending":"У тренді","home.forYou":"Для вас","home.newReleases":"Нові релізи","home.topCharts":"Топ 10","home.story":"Історія","home.welcome":"Ласкаво просимо до SocialBeats","feed.feed":"Стрічка","feed.newPost":"Новий пост","feed.like":"Вподобати","feed.comment":"Коментар","feed.share":"Поділитися","messages.messages":"Повідомлення","messages.newMessage":"Нове повідомлення","messages.calls":"Дзвінки","messages.online":"Онлайн","music.nowPlaying":"Зараз грає","music.playlist":"Плейлист","music.lyrics":"Текст пісні","music.songs":"Пісні","music.artists":"Виконавці","notifications.notifications":"Сповіщення","settings.settings":"Налаштування","settings.account":"Акаунт","settings.privacy":"Конфіденційність","settings.language":"Мова","settings.theme":"Тема","settings.security":"Безпека","settings.help":"Допомога","settings.about":"Про додаток","search.search":"Пошук","time.justNow":"щойно"}
}

def build_full_locale(partial, base):
    """Build a full locale file from partial translations and English base"""
    result = {}
    for section_key, section_val in base.items():
        result[section_key] = {}
        if isinstance(section_val, dict):
            for key, val in section_val.items():
                flat_key = f"{section_key}.{key}"
                if flat_key in partial:
                    result[section_key][key] = partial[flat_key]
                else:
                    result[section_key][key] = val  # fallback to English
        else:
            result[section_key] = section_val
    return result

for code, partial in TRANSLATIONS.items():
    filepath = os.path.join(LOCALES_DIR, f"{code}.json")
    if os.path.exists(filepath):
        print(f"[SKIP] {code}.json zaten mevcut, atlaniyor")
        continue
    partial_copy = {k: v for k, v in partial.items() if k != "lang"}
    full = build_full_locale(partial_copy, en)
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(full, f, ensure_ascii=False, indent=2)
    print(f"[OK] {code}.json olusturuldu")

print(f"\nToplam {len(TRANSLATIONS)} dil dosyasi islendi!")
