export const COUNTRIES = [
  { code: 'AF', name: 'Afganistan', flag: '🇦🇫' },
  { code: 'AL', name: 'Arnavutluk', flag: '🇦🇱' },
  { code: 'DZ', name: 'Cezayir', flag: '🇩🇿' },
  { code: 'AD', name: 'Andorra', flag: '🇦🇩' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴' },
  { code: 'AG', name: 'Antigua ve Barbuda', flag: '🇦🇬' },
  { code: 'AR', name: 'Arjantin', flag: '🇦🇷' },
  { code: 'AM', name: 'Ermenistan', flag: '🇦🇲' },
  { code: 'AU', name: 'Avustralya', flag: '🇦🇺' },
  { code: 'AT', name: 'Avusturya', flag: '🇦🇹' },
  { code: 'AZ', name: 'Azerbaycan', flag: '🇦🇿' },
  { code: 'BS', name: 'Bahamalar', flag: '🇧🇸' },
  { code: 'BH', name: 'Bahreyn', flag: '🇧🇭' },
  { code: 'BD', name: 'Bangladeş', flag: '🇧🇩' },
  { code: 'BB', name: 'Barbados', flag: '🇧🇧' },
  { code: 'BY', name: 'Belarus', flag: '🇧🇾' },
  { code: 'BE', name: 'Belçika', flag: '🇧🇪' },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿' },
  { code: 'BJ', name: 'Benin', flag: '🇧🇯' },
  { code: 'BT', name: 'Butan', flag: '🇧🇹' },
  { code: 'BO', name: 'Bolivya', flag: '🇧🇴' },
  { code: 'BA', name: 'Bosna Hersek', flag: '🇧🇦' },
  { code: 'BW', name: 'Botsvana', flag: '🇧🇼' },
  { code: 'BR', name: 'Brezilya', flag: '🇧🇷' },
  { code: 'BN', name: 'Brunei', flag: '🇧🇳' },
  { code: 'BG', name: 'Bulgaristan', flag: '🇧🇬' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫' },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮' },
  { code: 'KH', name: 'Kamboçya', flag: '🇰🇭' },
  { code: 'CM', name: 'Kamerun', flag: '🇨🇲' },
  { code: 'CA', name: 'Kanada', flag: '🇨🇦' },
  { code: 'CV', name: 'Yeşil Burun', flag: '🇨🇻' },
  { code: 'CF', name: 'Orta Afrika Cumhuriyeti', flag: '🇨🇫' },
  { code: 'TD', name: 'Çad', flag: '🇹🇩' },
  { code: 'CL', name: 'Şili', flag: '🇨🇱' },
  { code: 'CN', name: 'Çin', flag: '🇨🇳' },
  { code: 'CO', name: 'Kolombiya', flag: '🇨🇴' },
  { code: 'KM', name: 'Komorlar', flag: '🇰🇲' },
  { code: 'CG', name: 'Kongo', flag: '🇨🇬' },
  { code: 'CD', name: 'Kongo (DRC)', flag: '🇨🇩' },
  { code: 'CK', name: 'Cook Adaları', flag: '🇨🇰' },
  { code: 'CR', name: 'Kosta Rika', flag: '🇨🇷' },
  { code: 'CI', name: 'Fildişi Sahili', flag: '🇨🇮' },
  { code: 'HR', name: 'Hırvatistan', flag: '🇭🇷' },
  { code: 'CU', name: 'Küba', flag: '🇨🇺' },
  { code: 'CY', name: 'Kıbrıs', flag: '🇨🇾' },
  { code: 'CZ', name: 'Çekya', flag: '🇨🇿' },
  { code: 'DK', name: 'Danimarka', flag: '🇩🇰' },
  { code: 'DJ', name: 'Cibuti', flag: '🇩🇯' },
  { code: 'DM', name: 'Dominika', flag: '🇩🇲' },
  { code: 'DO', name: 'Dominik Cumhuriyeti', flag: '🇩🇴' },
  { code: 'EC', name: 'Ekvador', flag: '🇪🇨' },
  { code: 'EG', name: 'Mısır', flag: '🇪🇬' },
  { code: 'SV', name: 'El Salvador', flag: '🇸🇻' },
  { code: 'GQ', name: 'Ekvator Ginesi', flag: '🇬🇶' },
  { code: 'ER', name: 'Eritre', flag: '🇪🇷' },
  { code: 'EE', name: 'Estonya', flag: '🇪🇪' },
  { code: 'SZ', name: 'Esvatini', flag: '🇸🇿' },
  { code: 'ET', name: 'Etiyopya', flag: '🇪🇹' },
  { code: 'FJ', name: 'Fiji', flag: '🇫🇯' },
  { code: 'FI', name: 'Finlandiya', flag: '🇫🇮' },
  { code: 'FR', name: 'Fransa', flag: '🇫🇷' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦' },
  { code: 'GM', name: 'Gambiya', flag: '🇬🇲' },
  { code: 'GE', name: 'Gürcistan', flag: '🇬🇪' },
  { code: 'DE', name: 'Almanya', flag: '🇩🇪' },
  { code: 'GH', name: 'Gana', flag: '🇬🇭' },
  { code: 'GR', name: 'Yunanistan', flag: '🇬🇷' },
  { code: 'GD', name: 'Grenada', flag: '🇬🇩' },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹' },
  { code: 'GN', name: 'Gine', flag: '🇬🇳' },
  { code: 'GW', name: 'Gine-Bissau', flag: '🇬🇼' },
  { code: 'GY', name: 'Guyana', flag: '🇬🇾' },
  { code: 'HT', name: 'Haiti', flag: '🇭🇹' },
  { code: 'VA', name: 'Vatikan', flag: '🇻🇦' },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳' },
  { code: 'HU', name: 'Macaristan', flag: '🇭🇺' },
  { code: 'IS', name: 'İzlanda', flag: '🇮🇸' },
  { code: 'IN', name: 'Hindistan', flag: '🇮🇳' },
  { code: 'ID', name: 'Endonezya', flag: '🇮🇩' },
  { code: 'IR', name: 'İran', flag: '🇮🇷' },
  { code: 'IQ', name: 'Irak', flag: '🇮🇶' },
  { code: 'IE', name: 'İrlanda', flag: '🇮🇪' },
  { code: 'IL', name: 'İsrail', flag: '🇮🇱' },
  { code: 'IT', name: 'İtalya', flag: '🇮🇹' },
  { code: 'JM', name: 'Jamaika', flag: '🇯🇲' },
  { code: 'JP', name: 'Japonya', flag: '🇯🇵' },
  { code: 'JO', name: 'Ürdün', flag: '🇯🇴' },
  { code: 'KZ', name: 'Kazakistan', flag: '🇰🇿' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪' },
  { code: 'KI', name: 'Kiribati', flag: '🇰🇮' },
  { code: 'XK', name: 'Kosova', flag: '🇽🇰' },
  { code: 'KW', name: 'Kuveyt', flag: '🇰🇼' },
  { code: 'KG', name: 'Kırgızistan', flag: '🇰🇬' },
  { code: 'LA', name: 'Laos', flag: '🇱🇦' },
  { code: 'LV', name: 'Letonya', flag: '🇱🇻' },
  { code: 'LB', name: 'Lübnan', flag: '🇱🇧' },
  { code: 'LS', name: 'Lesoto', flag: '🇱🇸' },
  { code: 'LR', name: 'Liberya', flag: '🇱🇷' },
  { code: 'LY', name: 'Libya', flag: '🇱🇾' },
  { code: 'LI', name: 'Lihtenştayn', flag: '🇱🇮' },
  { code: 'LT', name: 'Litvanya', flag: '🇱🇹' },
  { code: 'LU', name: 'Lüksemburg', flag: '🇱🇺' },
  { code: 'MG', name: 'Madagaskar', flag: '🇲🇬' },
  { code: 'MW', name: 'Malavi', flag: '🇲🇼' },
  { code: 'MY', name: 'Malezya', flag: '🇲🇾' },
  { code: 'MV', name: 'Maldivler', flag: '🇲🇻' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱' },
  { code: 'MT', name: 'Malta', flag: '🇲🇹' },
  { code: 'MH', name: 'Marshall Adaları', flag: '🇲🇭' },
  { code: 'MR', name: 'Moritanya', flag: '🇲🇷' },
  { code: 'MU', name: 'Mauritius', flag: '🇲🇺' },
  { code: 'MX', name: 'Meksika', flag: '🇲🇽' },
  { code: 'FM', name: 'Mikronezya', flag: '🇫🇲' },
  { code: 'MD', name: 'Moldova', flag: '🇲🇩' },
  { code: 'MC', name: 'Monako', flag: '🇲🇨' },
  { code: 'MN', name: 'Moğolistan', flag: '🇲🇳' },
  { code: 'ME', name: 'Karadağ', flag: '🇲🇪' },
  { code: 'MA', name: 'Fas', flag: '🇲🇦' },
  { code: 'MZ', name: 'Mozambik', flag: '🇲🇿' },
  { code: 'MM', name: 'Myanmar', flag: '🇲🇲' },
  { code: 'NA', name: 'Namibya', flag: '🇳🇦' },
  { code: 'NR', name: 'Nauru', flag: '🇳🇷' },
  { code: 'NP', name: 'Nepal', flag: '🇳🇵' },
  { code: 'NL', name: 'Hollanda', flag: '🇳🇱' },
  { code: 'NZ', name: 'Yeni Zelanda', flag: '🇳🇿' },
  { code: 'NI', name: 'Nikaragua', flag: '🇳🇮' },
  { code: 'NE', name: 'Nijer', flag: '🇳🇪' },
  { code: 'NG', name: 'Nijerya', flag: '🇳🇬' },
  { code: 'KP', name: 'Kuzey Kore', flag: '🇰🇵' },
  { code: 'MK', name: 'Kuzey Makedonya', flag: '🇲🇰' },
  { code: 'NO', name: 'Norveç', flag: '🇳🇴' },
  { code: 'OM', name: 'Umman', flag: '🇴🇲' },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰' },
  { code: 'PW', name: 'Palau', flag: '🇵🇼' },
  { code: 'PS', name: 'Filistin', flag: '🇵🇸' },
  { code: 'PA', name: 'Panama', flag: '🇵🇦' },
  { code: 'PG', name: 'Papua Yeni Gine', flag: '🇵🇬' },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾' },
  { code: 'PE', name: 'Peru', flag: '🇵🇪' },
  { code: 'PH', name: 'Filipinler', flag: '🇵🇭' },
  { code: 'PL', name: 'Polonya', flag: '🇵🇱' },
  { code: 'PT', name: 'Portekiz', flag: '🇵🇹' },
  { code: 'QA', name: 'Katar', flag: '🇶🇦' },
  { code: 'RO', name: 'Romanya', flag: '🇷🇴' },
  { code: 'RU', name: 'Rusya', flag: '🇷🇺' },
  { code: 'RW', name: 'Ruanda', flag: '🇷🇼' },
  { code: 'KN', name: 'Saint Kitts ve Nevis', flag: '🇰🇳' },
  { code: 'LC', name: 'Saint Lucia', flag: '🇱🇨' },
  { code: 'VC', name: 'Saint Vincent ve Grenadinler', flag: '🇻🇨' },
  { code: 'WS', name: 'Samoa', flag: '🇼🇸' },
  { code: 'SM', name: 'San Marino', flag: '🇸🇲' },
  { code: 'ST', name: 'Sao Tome ve Prinsip', flag: '🇸🇹' },
  { code: 'SA', name: 'Suudi Arabistan', flag: '🇸🇦' },
  { code: 'SN', name: 'Senegal', flag: '🇸🇳' },
  { code: 'RS', name: 'Sırbistan', flag: '🇷🇸' },
  { code: 'SC', name: 'Seyşeller', flag: '🇸🇨' },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱' },
  { code: 'SG', name: 'Singapur', flag: '🇸🇬' },
  { code: 'SK', name: 'Slovakya', flag: '🇸🇰' },
  { code: 'SI', name: 'Slovenya', flag: '🇸🇮' },
  { code: 'SB', name: 'Solomon Adaları', flag: '🇸🇧' },
  { code: 'SO', name: 'Somali', flag: '🇸🇴' },
  { code: 'ZA', name: 'Güney Afrika', flag: '🇿🇦' },
  { code: 'KR', name: 'Güney Kore', flag: '🇰🇷' },
  { code: 'SS', name: 'Güney Sudan', flag: '🇸🇸' },
  { code: 'ES', name: 'İspanya', flag: '🇪🇸' },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰' },
  { code: 'SD', name: 'Sudan', flag: '🇸🇩' },
  { code: 'SR', name: 'Surinam', flag: '🇸🇷' },
  { code: 'SE', name: 'İsveç', flag: '🇸🇪' },
  { code: 'CH', name: 'İsviçre', flag: '🇨🇭' },
  { code: 'SY', name: 'Suriye', flag: '🇸🇾' },
  { code: 'TW', name: 'Tayvan', flag: '🇹🇼' },
  { code: 'TJ', name: 'Tacikistan', flag: '🇹🇯' },
  { code: 'TZ', name: 'Tanzanya', flag: '🇹🇿' },
  { code: 'TH', name: 'Tayland', flag: '🇹🇭' },
  { code: 'TL', name: 'Doğu Timor', flag: '🇹🇱' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬' },
  { code: 'TO', name: 'Tonga', flag: '🇹🇴' },
  { code: 'TT', name: 'Trinidad ve Tobago', flag: '🇹🇹' },
  { code: 'TN', name: 'Tunus', flag: '🇹🇳' },
  { code: 'TR', name: 'Türkiye', flag: '🇹🇷' },
  { code: 'TM', name: 'Türkmenistan', flag: '🇹🇲' },
  { code: 'TV', name: 'Tuvalu', flag: '🇹🇻' },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬' },
  { code: 'UA', name: 'Ukrayna', flag: '🇺🇦' },
  { code: 'AE', name: 'Birleşik Arap Emirlikleri', flag: '🇦🇪' },
  { code: 'GB', name: 'Birleşik Krallık', flag: '🇬🇧' },
  { code: 'US', name: 'Amerika Birleşik Devletleri', flag: '🇺🇸' },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾' },
  { code: 'UZ', name: 'Özbekistan', flag: '🇺🇿' },
  { code: 'VU', name: 'Vanuatu', flag: '🇻🇺' },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪' },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳' },
  { code: 'YE', name: 'Yemen', flag: '🇾🇪' },
  { code: 'ZM', name: 'Zambiya', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabve', flag: '🇿🇼' },
];
